### ISSUE TITLE
这个和build-actions是不是一样？

### ISSUE THREAD

**Issue by nianqing126** [281677160/autobuild#1]

**Comment by 281677160** [comment]
测试仓库，勿拉




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "281677160/autobuild"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月21日(星期二) 晚上8:16
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[281677160/autobuild] 这个和build-actions是不是一样？ (#1)





 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
